_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.11.5
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
                - 71
                - 84
                - 105
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
                - 71
                - 84
                - 105
            "3":
                - 23
                - 55
            "4": 3.11.5
            "5": 0.19.11
            "6": 4.49.0
            "8":
                - 3
                - 5
            "12": 0.19.11
            "13": windows-amd64
